### PR TITLE
solution: add bytedance golang solution

### PR DESCRIPTION
**Pull request by GuangmingLuo**
Go was introduced to ByteDance in 2014, and since then engineering teams across ByteDance have adopted Go to build products and services on a massive scale.

### CODE REVIEW

**Comment by GuangmingLuo** [comment]
@rsc hello, please help to review this, thanks

**Comment by GuangmingLuo** [comment]
@cameronbalahan hi, any progress ?

**Comment by GuangmingLuo** [comment]
hello, is there anyone in charge of this repo ?

**Comment by cameronbalahan** [comment]
Hi Guangmin, I will review this in the next two weeks. Apologies for not looking sooner; I'm out of office.

**Comment by GuangmingLuo** [comment]
@cameronbalahan hello, any progress ? One and a half month already :)

**Pull request closed without merging**
