### PR TITLE
website: add transparency to gopher images

### PR DESCRIPTION
**Pull request by Hinara**
(Only by adding alpha layer and converting jpg to png)

### CODE REVIEW

**Comment by Hinara** [comment]
@googlebot I signed it!

**Comment by Hinara** [comment]
The purpose is too avoid white outside when using a dark style, whether as an extension or as a custom godoc server
To avoid this
[https://puu.sh/Ez90Y.png](url)

**Comment by Hinara** [comment]
The goal of this changes is too add an alpha layer to gopher images to prevent big white square in the page.
https://puu.sh/Ez90Y.png
Currently I'm not touching too RGB layers, which make something like an outline which is might not be what it should be.
Should I also touch RGB layers to remove this white outline ?

**Comment by Hinara** [comment]
Preview with the current commit:
https://puu.sh/EGby7.png

**Comment by arezonavabiyan** [comment]
Perfect :)
https://www.archivenews.ir

**Pull request closed without merging**
